### ISSUE TITLE
settle on game idea

### ISSUE THREAD

**Issue by guidopetri** [guidopetri/pyweek-35#1]
```
in the shadows
  red light green light and you are the enemy in the shadows
  detective noir mystery with shadows theme
  alien world, sun too hot, moving from one tree shadow to another
  always dark survival maze, limited number of light-up items
```

**Comment by guidopetri** [comment]
top down 2d, light circle around you keeps shrinking, non-tech-y: candles, 

story is: you were on a hike/picnic (with a friend?), got lost in the woods, find your way. only have set amount of matches/candles/single flashlight (limited battery)/picnic gear. also have a jar? to find fireflies that give blinking lights, bioluminescent mushrooms (make whole screen wavy - under the influence), owl who you follow but you only see their eyes (guide you in the next general direction), moments of moonlight,

**Comment by kllemon** [comment]
Somehow accidently find yourself in an enchanted forest where if you show fear you're turned to stone?

matches that you can burn that give you good light for a short time, but if you save them you can make torches that burn brighter for longer
you can catch glowing snails to use for light but they just light the immediate area and then slowly scurry into the woods
you can catch lightning bugs in your jar but they only dimly light a small area (larger area than snails though) and slowly blink (1 lightning bug at a time)
A rain mode where you walk slower and you cant light matches or make a torch, and no bugs or snails spawn but lightning flashes occasionally to show you where to go
If you come across an owl within your light circle it will take off and fly across the screen in the general direction you should go?
Moonlight moments where the clouds part and you can easily see your way in the forest for a short time in blue light

No electric technology i think. ye olden days or something

If you move too far into the thick of the forest you lose all of you "courage" (HP) until you're "scared stiff" and are turned to stone and lost forever

The end is a road which you follow for a short ways until help (horse drawn traveling cart with oil lamps?) happens to come across your way, the end!

Endless mode?
Hard mode?

**Comment by kllemon** [comment]
Maze with a path that moves in all directions, with dead ends.

The edges of the "safe" path are lined with tree canopy. If you stray out of the "safe path" and wander into the tree canopy, you begin to lose HP. If you go too deep into the tree canopy it's instant game over.

Some sort of indicator for usable items

We should think of a way for players to be able to regain some HP. Im thinking maybe those moonlight moments when you can see the whole screen for a short time?
